### ISSUE TITLE
Gen 5 Time Finder doesn't filter natures unless "Shiny Only" is checked

### ISSUE THREAD

**Issue by OfficialTheosis** [Bambo-Rambo/RNGReporter#4]
I believe I have encountered an issue when trying to RNG manipulate IVs and PID in BW2. In my case I was trying to go for a 5/6 31 IV starter with Adamant nature, not shiny. When trying to find a seed, the results do not seem to care about the nature I specified. You can verify this by putting the found seed into the normal RNG reporter and observing that the IVs match up, but the nature does not.

**Comment by Bambo-Rambo** [comment]
Nature and PID determination use a different RNG. Unless you are looking for a shiny, the tool will only care about the desired IVs. You can try multiple seeds in the main window until you find the desired nature in early frames. Not optimal since you don't have Chatots but that's how reporter has been since its release and I don't feel like changing this at the moment.
